using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Content.Client.UserInterface;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._RMC14.Intelligence.UI;

[GenerateTypedNameReferences]
public sealed partial class IntelClueDisplayWindow : DefaultWindow
{
    private readonly IntelClueDisplayBoundUserInterface _owner;
    public IntelClueDisplayWindow(IntelClueDisplayBoundUserInterface owner)
    {
        _owner = owner;
        Robust.Client.UserInterface.Controls.OptionButton a = new();
    }

    
    

}
